### PR TITLE
add volume mounts as per 2.9 service broker api spec

### PR DESCRIPTION
**Pull request by cwlbraa**
see: http://docs.cloudfoundry.org/services/api.html#binding and http://docs.cloudfoundry.org/services/api.html#binding

this api isn't stable yet, so there will be another one of these PRs, but we're pointing at this fork for now and would love to be back on master :)

### CODE REVIEW

**Comment by mariantalla** [comment]
Hi @cwlbraa, thank you for adding volume mounts to the `Binding` struct. Please could you add a test? There is a context for binding here: https://github.com/pivotal-cf/brokerapi/blob/1ff35433ffe641849fd4c614537bb5c94b8240c5/api_test.go#L885

cc: @jamesjoshuahill

**Comment by avade** [comment]
Going to icebox this until tests are added.

**Comment by cwlbraa** [comment]
@mariantella @avade hey all, what behavior would you have me test? just looking for an example of an plain english assertion, given that the change is only to types and doesn't actually /do/ anything.

**Comment by mariantalla** [comment]
Thank you @cwlbraa , this has been now merged.

**Pull request merged**
