### PR TITLE
Add instances_retrievable/bindings_retrievable catalog fields added in v2.14

### PR DESCRIPTION
**Pull request by drnic**
- https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md\#fetching-a-service-binding
- https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md\#fetching-a-service-instance

### CODE REVIEW

**Comment by jacknewberry** [comment]
The catalog unit tests are failing. They should either expect the new fields, or the new fields should be tagged 'omitempty'.

**Comment by jacknewberry** [comment]
```
$ ginkgo -r

...
Summarizing 3 Failures:

[Fail] Service Broker API catalog endpoint [It] returns valid catalog json
/Users/pivotal/workspace/on-demand-service-broker-release/src/github.com/pivotal-cf/brokerapi/api_test.go:278

[Fail] Catalog Service JSON encoding [It] uses the correct keys
/Users/pivotal/workspace/on-demand-service-broker-release/src/github.com/pivotal-cf/brokerapi/catalog_test.go:64

[Fail] Catalog Service [It] encodes the optional 'requires' fields
/Users/pivotal/workspace/on-demand-service-broker-release/src/github.com/pivotal-cf/brokerapi/catalog_test.go:107

Ran 219 of 219 Specs in 0.166 seconds
FAIL! -- 216 Passed | 3 Failed | 0 Pending | 0 Skipped --- FAIL: TestAPI (0.17s)
FAIL

Ginkgo ran 1 suite in 3.143985371s
Test Suite Failed
```

**Comment by drnic** [comment]
I'm sorry about. I'm surprised at myself that I submitted the PR with tests failing.

**Comment by drnic** [comment]
I've rebased, added `omitempty`, and tests pass.

**Comment by jacknewberry** [comment]
Excellent. Thank you.

**Pull request merged**
