### PR TITLE
chore: Update to ginkgo v2 and lager v3

### PR DESCRIPTION
**Pull request by silvestre**
I upgraded

- `onsi/ginkgo` to `v2`
- `cloudfoundry/lager` to `v3`

in one PR as I couldn't get the tests to pass while only updating lager. I hope this PR is fine anyway.

Additionally, as the update of the `lager` library modifies the signature of [`NewApiHandler`](https://github.com/pivotal-cf/brokerapi/blob/main/handlers/api_handler.go#L35) to require a `v3` `lager.Logger` introduces a breaking change I believe this PR also requires bumping the major version. I have added a [second commit](https://github.com/pivotal-cf/brokerapi/pull/218/commits/9f6b1b7520b2ec2b7f430a03de3205a66ccf9ad3) to do this.

Thank you for considering it.

### CODE REVIEW

**Comment by pivotal-marcela-campo** [comment]
Thanks @silvestre for this PR, we'll review this shortly.

**Comment by silvestre** [comment]
@blgm @pivotal-marcela-campo : I rebased this PR to keep it mergeable - do you think that this change could go in?

**Comment by pivotal-marcela-campo** [comment]
Hi @silvestre , definitely. Just one question, would you need us to release right away or can that wait a few weeks to bundle this with other dependency updates?

**Comment by silvestre** [comment]
Hi @pivotal-marcela-campo , no we can wait for the release, thanks!

**Pull request merged**
